Fix export of chord symbols with realized durations
cuthbertLab/music21 pull request #1166
Opened 2021-11-13 17:10 UTC by jacobtylerwalls

Fixes #963

2022-01-12 00:26 UTC, mscuthbert commented
This seems correct for "writeAsChord = False" but not for "writeAsChord = True"  I don't know that we have output tests for that in musicxml.  But skipping those Chords' durations seems incorrect

It also makes me realize that N.C. should allow for "writeAsChord = True" but it should make a rest instead of a Chord.

2022-01-12 00:28 UTC, mscuthbert requested changes
Check with writeAsChord = True or add tests for that.  Does this also impact RomanNumerals?

2022-01-12 00:28 UTC, mscuthbert commented on music21/musicxml/m21ToXml.py
> +        if 'GeneralNote' in classes and 'Harmony' not in classes:
Likely to fail if writeAsChord = False.

2022-01-16 23:49 UTC, jacobtylerwalls commented
> But skipping those Chords' durations seems incorrect

Thanks for the catch.

> Does this also impact RomanNumerals?

yes, if anyone has been setting duration on a RomanNumeral, then they should be getting better musicxml output, no stray offset and backup tags corrupting the output.

> It also makes me realize that N.C. should allow for "writeAsChord = True" but it should make a rest instead of a Chord.

Smart! See next PR.

2022-02-07 17:55 UTC, merged

2022-02-07 17:55 UTC, mscuthbert commented
looks great to me.  THANKS!