Write roman ts and repeats
cuthbertLab/music21 pull request #1393
Opened 2022-08-17 14:15 UTC by MarkGotham

Write complement to #1378 along with a bit of clean up

2022-08-17 23:16 UTC, mscuthbert requested changes
Please see comments on removing tested/documented code without replacements.

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        >>> p.insert(m)
-1; I'm deemphasizing using insert without an offset.  Unnecessary change.

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        Mid-measure repeats are an open issue (much wider than rntxt).
remove editorial

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        >>> m2 = stream.Measure(number=2)
What is this case demonstrating?

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +            thisMeasureNumber = thisMeasure.measureNumberWithSuffix()  # now str
typing.  Especially for anything called "...Number" that is actually a string.

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +                    measureString += f' {chordString}'
please explain the change here -- we're removing tested and testable code for a single RN and replacing it with nested code that is hard to test.  -1

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> -
removal of well-explained, stable, and tested code for undocumented and untested routines.  negative.

2022-08-17 23:16 UTC, mscuthbert commented on music21/romanText/writeRoman.py
>  # ------------------------------------------------------------------------------
removal of tests with no corresponding replacement.  -1

2022-09-02 14:39 UTC, MarkGotham commented
Ok, noted.

The mass deletions are an attempt at simpler solutions and strike me as a good fit for the contributing docs' invitation to remove 30+ lines when 1 will do nicely. All the same, while I have misgiving about `rnString` (for that reason among others), I'll go ahead and reinstate it with the minimum changes to accommodate new tokens (i.e., repeat marks).

For reference, the process is about the addition of specific tokens in a specific order.
- measure (required)
- (optional) start repeat
- RNs (with beat except for b1, at least one required)
- (optional) end repeat

2022-10-05 10:54 UTC, MarkGotham commented
This PR has been superseded by another, subsequent one for the same issue at #1435.

I wonder if there's an integration action for checking new PRs against those in progress that would prevent this?

In any case, I've been through to pick them apart and what remains as new here is simply:
- adding a doc test and
- one case of specifying `insert()` at position 0 (as requested) 
- misc clean up and clarification

A small contributions for sure, but a positive one, and makes this (1393) ready for closure.

Let me know if you spot any issues / anything missing.

2022-10-05 20:36 UTC, mscuthbert requested changes
The contributions here are enough to still merge after the changes requested are made.

If you know of an easy tool that can prevent duplicated work, happy to add it.

2022-10-05 20:36 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        >>> p.insert(m)
This is still in the current version.  Unresolved.

2022-10-05 20:36 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        >>> testCase.combinedList[-1]
Needs blank line between text and doctest.

2022-10-05 20:36 UTC, mscuthbert commented on music21/romanText/writeRoman.py
> +        >>> testCase.combinedList[-2]
As above

2022-10-07 01:43 UTC, mscuthbert approved these changes
LGTM.  Thanks!

2022-10-07 01:44 UTC, merged