In kern allow non-eighth type & non-slashed grace notes, improve default duration of non-first chord notes, decrease import time by ~15%
cuthbertLab/music21 pull request #1684
Opened 2024-01-19 12:13 UTC by alexandermorgan

This PR has some very minor substantive changes with accompanying tests and several small optimizations for kern import

Substantive changes:
1. Grace notes without slashes are now detected when two lowercase q's are present
2. Grace notes apply their stated duration rather than always having eighth note representations. About these two grace note points, you can see in [this example](https://verovio.humdrum.org/?t=KiprZXJuCjE2YS1xCjJnCjhmI3FxCjJnCj09CiotCg==) that humdrum is sensitive to the stated duration of a grace note, and also that the second q will omit the slash.
3. In chords where only the first note has a stated duration, the other notes of the chord will take on the duration of the first note. The same exact duration object is used, similar to how chords already currently reuse the duration of their first note. Although standard humdrum syntax calls for a duration on each note of a chord, you can see [here](https://verovio.humdrum.org?t=KiprZXJuCjRnIDRiCjRmIGEKMmUgZwoxZCBmCj09CiotCg==) that when only the first note has a stated duration, other chords will use the same rather than defaulting to a quarter note.

Kern import optimizations (mostly in hdStringToNote)
1. `if str.count('x'):` becomes `if 'x' in str:`
2. Move duration parsing of notes to the beginning of hdStringToNote so that notes and rests can be instantiated with their correct duration from the beginning rather than being created and then having their duration replaced. This prevents an unused default duration from being created on each note and rest. Even better for chords, this pr makes them inherit the duration of their first note when the chord is created rather than right after creation, which means that instead of creating 1 unused duration per chord, now no new ones are created. I didn't check, but this super simple change for chords could be a quick and easy win for other import types if they construct chords in the same way.
3. Combine the normal duration and rational duration regexes into one. Likewise for note name and accidental searches.
4. Use walrus operator where possible to avoid duplicating operations
5. Add short-circuit to stop processing a note/rest if all the characters have been accounted for after the duration and note name/accidental have been processed
6. Comment out parsing that only results in pass statements
7. Memoize the duration and note name regex searches inside of hdStringToNote. New durations, notes, and rests are still instantiated for each event.

2024-03-19 18:30 UTC, alexandermorgan commented
Is there any input on this pr? It fixes two bugs for me when reading kern files so I would like to see it integrated if possible. I can also file those two bugs as issues if that would help. Thanks.

2024-04-25 22:24 UTC, mscuthbert commented
Hi Alex -- as I've mentioned on the list, I'm taking a hiatus from music21 except for paid support, unless I happen to have a bit of extra time.  I'll try to get this when I can.  Note that there's some conflict w/ the PR of Tim #1693 -- whichever gets merged first will need to have some edits on the other.

2024-04-25 22:34 UTC, mscuthbert requested changes
Hi  -- sorry but I cannot accept this in the state it is in because I cannot follow the logic that it is supposed to use to speed up.  The refactor adds much more complexity to an already overly complex routine.

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +def _noteMemos(contents):
new music21 routines require typing.  Can you type the input and output of this routine?

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +def hdStringToNote(contents, defaultDuration=None):
add typing at least to the new attribute (but it'd be kind to add typing to all)

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +def _noteMemos(contents):
Give some docs about what this does.

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +    return (dur_regex, dotCount, matchedNote, step, accountedFor)
don't mix underscore and camelCase in internal variable names.  Choose one or the other.

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +            dur = duration.Duration(.5, dots=dotCount)
style: 0.5 not .5

2024-04-25 22:34 UTC, mscuthbert commented on music21/humdrum/spineParser.py
> +        foundNumber, foundRational = dur_regex.groups()
all of this takes an already very complex set of routines and makes them even more complex -- now with a set of nested if statements.  Together with the rewriting of the count routines, I can't make heads or tails of what has changed.  Please refactor into a routine that gets the duration from contents and one that gets the pitch from contents.  I have no idea what "accountedFor" means or what a dur_regex is supposed to represent.

2024-04-30 15:33 UTC, closed without merging