Small simplifications and speed-ups
cuthbertLab/music21 pull request #1693
Opened 2024-03-01 11:51 UTC by TimFelixBeyer

Just some small tweaks in the spirit of #1631 and #1683 that don't change the functionality.

2024-04-25 22:01 UTC, mscuthbert commented
closing and reopening to update lint.

2024-04-25 22:10 UTC, mscuthbert requested changes
Hi Tim -- really great 90%, but I've asked a couple of times to stop changing code style just because it could be written in another way, and I'm now going to hold off on the PR until those lines are changed back.  They don't save the processor any significant time, but they eat up my time in reviewing.

2024-04-25 22:10 UTC, mscuthbert commented on music21/scale/__init__.py
> +        return self.tonic is not None
please stop changing these.  I've asked a couple of times already.

2024-04-25 22:10 UTC, mscuthbert commented on music21/scale/__init__.py
> +        if (isinstance(other, self.__class__)
as above.  Please stop changing code style that does not increase speed, just to match your code style.

2024-04-29 22:12 UTC, mscuthbert commented
THANKS!  Huge appreciation.  Merging!

2024-04-29 22:12 UTC, mscuthbert approved these changes

2024-04-29 22:12 UTC, merged

2024-04-30 06:22 UTC, TimFelixBeyer commented
> Hi Tim -- really great 90%, but I've asked a couple of times to stop changing code style just because it could be written in another way, and I'm now going to hold off on the PR until those lines are changed back. They don't save the processor any significant time, but they eat up my time in reviewing.

I’m not doing this to annoy you, I usually just work with a very heavily modified version of m21 and sometimes some of my other changes slip in. I will be more careful when making PRs to music21 main in the future to make sure only the most important changes are included.